# Generated by Django 5.2.5 on 2025-09-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DatabaseLogic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="name",
            field=models.TextField(),
        ),
    ]
